import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ReactDOM from 'react-dom';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 1. PRECONNECT: Establish early connections to important third-party origins
  // Example: If you load images/fonts/APIs from an external server
  ReactDOM.preconnect('https://fonts.googleapis.com', {
    crossOrigin: 'anonymous',
  });
  ReactDOM.preconnect('https://your-custom-backend-api.com', {
    crossOrigin: 'use-credentials',
  });

  // 2. PRELOAD: Request critical assets at the very top of the waterfall
  // Example: Preloading your biggest hero image (LCP) so it paints faster
  // ReactDOM.preload('/images/hero-bg.webp', { as: 'image' });

  // Example: Preload external vital scripts
  // ReactDOM.preload('https://cdn.jsdelivr.net/npm/some-critical-script.js', { as: 'script' });

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
