#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)

# Only enforce strict commit message rules on main and develop branches
  if head -1 "$1" | grep -qE "Merge .{1,}$"; then
    echo $'\e[1;36m Skipping commit check.\e[0m\n'
    exit 0
  fi
  if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|hotfix|asap|deploy)(\(.+?\))?: [a-z0-9]"; then
      echo $'\e[1;31m Aborting commit. Your commit subject must be in the format of feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert|hotfix|asap|deploy)(\(.+?\))?: [a-z0-9].\e[0m\n' >&2
      exit 1
  fi
  if head -1 "$1" | grep -qE "\.$"; then
      echo $'\e[1;31m Aborting commit. Your commit message should not end with a period.\e[0m\n' >&2
      exit 1
  fi
  if ! head -1 "$1" | grep -qE "^.{1,200}$"; then
      echo $'\n\e[1;31m Aborting commit. Your commit message is too long.\n\e[0m' >&2
      echo $'\e[42m Please keep your commit message short i.e. only upto 200 characters.\e[0m\n'
      exit 1
  fi
