#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
  # Check if package.json or pnpm-lock.yaml were changed in the merge
  changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

  check_run() {
  echo "$changed_files" | grep --quiet "$1" && eval "$2"
  }

  # Run pnpm install if the lockfile changed
  echo "\e[1;36mChecking for dependency changes on $branch...\e[0m"
  check_run "pnpm-lock.yaml" "pnpm install"
fi
