#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
  echo "\e[1;31m Direct commit to $branch is not allowed! Please create a feature branch.\e[0m"
  exit 1
fi

npx lint-staged
pnpm exec tsc --noEmit
