#!/bin/sh
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ] || [ "$branch" = "develop" ]; then
  echo "\e[1;31m Direct push to $branch is not allowed! Please use a Pull Request.\e[0m"
  exit 1
fi
